#!/usr/bin/env python3
"""
Precompute interference sweep data for the interactive explainer.

Implements a simple linear-attention associative memory: M ← M + v_i · k_i^T
Sweeps over memory dimensions and association counts, measuring recall accuracy.

Output: data/interference_sweep.json
"""

import json
import numpy as np
import os

def random_unit_vector(dim, rng):
    """Generate a random unit vector of given dimension."""
    v = rng.standard_normal(dim)
    v /= np.linalg.norm(v)
    return v

def cosine_similarity(a, b):
    """Compute cosine similarity between two vectors."""
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    if norm_a < 1e-10 or norm_b < 1e-10:
        return 0.0
    return float(np.dot(a, b) / (norm_a * norm_b))

def run_experiment(dim, n_associations, rng, n_trials=20):
    """
    Run multiple trials of storing n_associations in a d×d memory matrix.
    Returns mean and std of cosine similarity across all queries and trials.
    """
    similarities = []

    for _ in range(n_trials):
        M = np.zeros((dim, dim))
        keys = []
        values = []

        # Store associations
        for i in range(n_associations):
            k = random_unit_vector(dim, rng)
            v = random_unit_vector(dim, rng)
            keys.append(k)
            values.append(v)
            M += np.outer(v, k)  # Hebbian write: M ← M + v · kᵀ

        # Query each stored key
        for i in range(n_associations):
            retrieved = M @ keys[i]  # Linear readout
            sim = cosine_similarity(retrieved, values[i])
            similarities.append(sim)

    return {
        "mean": float(np.mean(similarities)),
        "std": float(np.std(similarities)),
        "min": float(np.min(similarities)),
        "max": float(np.max(similarities)),
    }

def main():
    rng = np.random.default_rng(42)

    dims = [4, 8, 16, 32, 64]
    results = {}

    for d in dims:
        print(f"Sweeping dim={d}...")
        dim_results = []
        # Sweep from 1 association up to 4× the dimension
        max_n = 4 * d
        step = max(1, d // 8)
        n_values = list(range(1, max_n + 1, step))
        # Always include d (the "capacity" point) and a few extras
        for special in [d // 2, d, d * 2, d * 3, max_n]:
            if special > 0 and special <= max_n and special not in n_values:
                n_values.append(special)
        n_values = sorted(set(n_values))

        for n in n_values:
            result = run_experiment(d, n, rng)
            dim_results.append({
                "n_associations": n,
                "capacity_ratio": round(n / d, 3),
                **result
            })

        results[str(d)] = {
            "dim": d,
            "max_associations": max_n,
            "data": dim_results
        }

    # Also compute a "capacity cliff" summary: for each dim,
    # find the n where mean similarity drops below 0.9, 0.7, 0.5
    capacity_summary = {}
    for d_str, d_data in results.items():
        d = d_data["dim"]
        thresholds = {"0.9": None, "0.7": None, "0.5": None}
        for point in d_data["data"]:
            for thresh_str, thresh_val in [("0.9", 0.9), ("0.7", 0.7), ("0.5", 0.5)]:
                if thresholds[thresh_str] is None and point["mean"] < thresh_val:
                    thresholds[thresh_str] = point["n_associations"]
        capacity_summary[d_str] = {
            "dim": d,
            "cliff_at_0.9": thresholds["0.9"],
            "cliff_at_0.7": thresholds["0.7"],
            "cliff_at_0.5": thresholds["0.5"],
        }

    output = {
        "description": "Precomputed interference sweep for outer-product associative memory. "
                       "Each entry shows mean cosine similarity between retrieved and true values "
                       "as a function of memory dimension (d) and number of stored associations (n).",
        "mechanism": "M ← M + v · kᵀ (Hebbian/outer-product write). Readout: v̂ = M · q.",
        "label": "PRECOMPUTED — not live inference. Generated by scripts/precompute_interference.py.",
        "sweep": results,
        "capacity_summary": capacity_summary
    }

    os.makedirs("data", exist_ok=True)
    with open("data/interference_sweep.json", "w") as f:
        json.dump(output, f, indent=2)

    print(f"\nSaved to data/interference_sweep.json")
    print(f"\nCapacity summary:")
    for d_str, summary in capacity_summary.items():
        print(f"  dim={summary['dim']}: "
              f"drops below 0.9 at n={summary['cliff_at_0.9']}, "
              f"below 0.7 at n={summary['cliff_at_0.7']}, "
              f"below 0.5 at n={summary['cliff_at_0.5']}")

if __name__ == "__main__":
    main()
